[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"

[workspace]
resolver = "2"
members = [
  "src/rs_lib",
]

[patch.crates-io]
deno_cache_dir = { path = "../deno_cache_dir/rs_lib" }